### ISSUE TITLE
Disable global overwriting

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es-module-loader#443]
It may make sense for the polyfill here to only write to `window.SystemPolyfill` and not create a `window.System`. Because this project always requires functionality built on top of it to create a useful loader, these specific loader implementations can then handle the global assignment cases.

This is in line with this project being a starting point for loader construction over something end-users use directly.

**Comment by joeldenning** [comment]
Or would it make sense to, rather, for this polyfill to be a no-op if `System.loader`, `Reflect`, etc. are already implemented?

**Comment by guybedford** [comment]
@joeldenning there may be implementation differences in some cases so that the polyfill may still be desired over native implementations if there happen to be any implementation gaps. Just like how Promises had better perf and rejection handling through polyfills until the native implementations caught up. Providing an alternative polyfill global in some form is useful for these sorts of scenarios.

**Comment by guybedford** [comment]
The 1.0 release provides no global setting.
