### ISSUE TITLE
strict v non-strict builds

### ISSUE THREAD

**Issue by guybedford** [ModuleLoader/es-module-loader#467]
Since we're implementing to the spec based on correctness, it would be nice to have a globally-scoped variable, `STRICT`, which is included as a boolean check whenever doing checks that one wouldn't want in a high-performance production loader where correctness is not important.

We can then run two builds of the loader through dead code removal that set STRICT=false and STRICT=true respectively to get different builds for the different requirements here.

**Comment by joeldenning** [comment]
Would https://github.com/mishoo/UglifyJS#use-as-a-code-pre-processor be the best way to do this? And perhaps make es6-module-loader.dev.js be run with `STRICT` == true, and have es6-module-loader.js be the one with `STRICT` set to false?

**Comment by joeldenning** [comment]
Also, would we want tests to be run on the code in both modes? Or would we just make very sure that nothing that uses the `STRICT` variable would have any logic/implementation in it.

**Comment by guybedford** [comment]
Yes exactly like that, although perhaps as a completely separate unminified build so we have `es6-module-loader-strict.src.js` and `es6-module-loader.src.js` or something similar? Then we should run the tests on both as well ideally.
