### ISSUE TITLE
Update wiki to reflect deprecation of `locate` and new role of `normalize`

### ISSUE THREAD

**Issue by masaeedu** [ModuleLoader/es-module-loader#473]
The latest docs [here](https://github.com/ModuleLoader/es6-module-loader/blob/ab91a0e818a81ddf529ee204bc33376d1d27b1ae/docs/loader-extensions.md) are out of date with respect to the [deprecation of the `locate` hook](https://github.com/whatwg/loader/issues/52).

**Comment by guybedford** [comment]
The current documentation reflects the older specification that the stable branch of this project is based on. These documentation updates would be included on the 1.0 branch.
