### ISSUE TITLE
Upgrade Node version

### ISSUE THREAD

**Issue by probins** [ModuleLoader/es-module-loader#503]
atm `package.json` in master is specifying >=0.8.0 under 'engines', whereas `.travis.yml` is using 'stable' under 'node_js' but 0.10 in the matrix section. Travis uses nvm, where the 'stable' tag is now deprecated in favour of 'node'. I would suggest updating this to use at least v4, though preferably v6. v4 and above includes Promise support, so the `when` dependency could be removed.

**Comment by guybedford** [comment]
v4 and v6 only makes sense.
