### ISSUE TITLE
Add dist to .gitignore?

### ISSUE THREAD

**Issue by probins** [ModuleLoader/es-module-loader#506]
Readme says I shouldn't edit `dist/*` but `dist/*` are needed to run tests, and if I run grunt to generate them they will be included in any new branch uploaded to Github. This probably isn't wanted, so shouldn't dist be added to `.gitignore`?

**Comment by guybedford** [comment]
dist is currently checked in for releases only, and not for commits between releases.

**Comment by probins** [comment]
this has been done for 1.0, so I'll close this
