### ISSUE TITLE
Shouldn't import() return default export?

### ISSUE THREAD

**Issue by probins** [ModuleLoader/es-module-loader#514]
Not sure if this is intentional or not. I'm busy converting CJS to ES6/System.register for use in the register loader, and find some differences in the way default exports are imported. I was using `module.exports={...}`, which sets the module namespace to `{...}`. With ES6 I'm using `export default ...`, which creates a namespace called `default`; to import in CJS this needs `require(...).default`. Fair enough. With ES6/register import the `.default` is not necessary. Again, ok. But if I use `loader.import` I have to specify `default` again: `loader.import(...).then(function(m){...m.default...})`. Is this correct?

**Comment by guybedford** [comment]
This was a convenience in SystemJS that won't exist in real ES module environments.

**Comment by probins** [comment]
on testing this out a bit more, I've decided this is correct, though the handling of defaults in ES6 is a bit confusing. If I take the example in https://github.com/systemjs/systemjs/blob/master/docs/es6-modules-overview.md#default-import-and-export, `export default function foo()` effectively means 'export the foo function as "default"'' and is the same as `export default function()` which means 'export the anonymous function as "default"'. You would probably import this with `import foo`, but as in the example you can call the imported default anything you like. `import customName from` effectively means  `import default as customName`. With `import()` you don't have this rename ability: `export function foo` would be imported with `import(...).then(function(module) {module.foo()}`, whereas `export default function` is imported with `import(...).then(function(module) {module.default()}`.

Probably be a good idea to expand the demo to explore these different options - though whether I'll have time for that is another matter :-)
