### ISSUE TITLE
Link documentation error in npm

### ISSUE THREAD

**Issue by felipesousa** [ModuleLoader/es-module-loader#521]
Section npm who has about Documentation is broken, returning not found! :/

**Comment by guybedford** [comment]
@felipesousa which exact link is not working here for you? A PR is welcome as well if it's easier.

**Comment by felipesousa** [comment]
Currently, this package in npm has a readme.md different from what currently exists in the project, so I saw, the documentation that is in npm does equality in readme.md that is in branch "0.17" (https://github.com/ModuleLoader/es-module-loader/tree/0.17), I believe that the package (in this case, readme) must be updated by readme.md which is in the master branch for npm. In that case, updating the package in npm, solves the "problem", I believe.

**Comment by guybedford** [comment]
@felipesousa the 0.17 branch is the previous version of this project. The documentation here and on npm is now all for the 1.0.0 branch (https://www.npmjs.com/package/es-module-loader). Let me know if that clarifies for you.

**Comment by felipesousa** [comment]
@guybedford yes, thanks for you response! hug`s!
