### ISSUE TITLE
Loader conflicts with Babel's interop

### ISSUE THREAD

**Issue by ghempton** [ModuleLoader/es-module-loader#526]
The change introduced here: https://github.com/ModuleLoader/es-module-loader/commit/f2bb1395231e017594dd2e2ff94af5086a92c854 introduced a regression when dealing with Babel's own interop with cjs.

See here for an example: https://github.com/ghempton/systemjs-builder-test/tree/interop (need to `jspm link` a version of systemjs that is built with this most recent build of es-module-loader). The issue is that SystemJS removes  the `__esModule` flag that is read by babel's generated `_interopRequireDefault`

**Comment by guybedford** [comment]
@ghempton thanks for your feedback getting this adjusted introp ironed out. I've added a possible fix in https://github.com/ModuleLoader/es-module-loader/commit/7bb7ff3b4d5104acf9610d08282a30e927d97c48. Will be testing this further before release.

**Comment by guybedford** [comment]
Released in 2.1.0.
