### ISSUE TITLE
Unable to load babel-types/lib/constants.js

### ISSUE THREAD

**Issue by ghempton** [ModuleLoader/es-module-loader#529]
This looks like it could be related to #526. In this case I am unable to get plugin-babel itself working in a barebones project: https://github.com/ghempton/systemjs-builder-test/tree/babel (run `./node_modules/.bin/testem` to see the error):

![image](https://cloud.githubusercontent.com/assets/8994/22949738/1a73273a-f2b8-11e6-98eb-b60227b1d1ba.png)

**Comment by guybedford** [comment]
When I run this I get the following error here instead:

```javascript
Uncaught (in promise) Error: Unable to dynamically transpile ES module
   A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
  Instantiating http://localhost:7357/jspm_packages/npm/systemjs-plugin-babel@0.0.21/babel-helpers/classCallCheck.js
  Loading http://localhost:7357/src/start.js
  Loading app/start
    at transpile (system.src.js:3660)
    at system.src.js:3443
```

**Comment by guybedford** [comment]
After configuring the transpiler, and running the master build of SystemJS, I don't get any further errors. So this may have been fixed already, but let me know if I'm missing something.

**Comment by guybedford** [comment]
Just let me know if you're still noticing this with the latest 0.20.8 SystemJS release.

**Comment by ghempton** [comment]
I updated to 0.20.8 and that particular issue has gone away. However, there is a separate issue that I'm seeing here:

![image](https://cloud.githubusercontent.com/assets/8994/23034876/2572b68e-f432-11e6-9093-3133c370c0ab.png)

I've updated the branch here https://github.com/ghempton/systemjs-builder-test/tree/babel and you should be able to see it just by running `npm start`.

**Comment by guybedford** [comment]
I've resolved the above in the Babel plugin in https://github.com/systemjs/plugin-babel/commit/c72965ba5acdfd99cc769eacb24d3ced361aaeff. I also created a separate SystemJS issue to check the normalization behaviour when I've got a little more time.

Closing this for now, thanks for all your help catching these cases. Please keep it coming if you notice anything else.
