### ISSUE TITLE
Error: Cannot redefine property: __useDefault

### ISSUE THREAD

**Issue by MaximBalaganskiy** [ModuleLoader/es-module-loader#531]
After upgrading my Aurelia project to SystemJs 0.20.7 I started getting the following error

`Uncaught (in promise) Error: Cannot redefine property: __useDefault
  Evaluating https://localhost:44344/jspm_packages/npm/aurelia-framework@1.0.8/aurelia-framework.js
  Loading https://localhost:44344/jspm_packages/npm/aurelia-framework@1.0.8/aurelia-framework.js
    at Function.defineProperty (<anonymous>)
    at eval (https://localhost:44344/jspm_packages/npm/aurelia-framework@1.0.8/aurelia-framework.js:19:12)
    at Array.forEach (native)
    at Object.eval (https://localhost:44344/jspm_packages/npm/aurelia-framework@1.0.8/aurelia-framework.js:17:32)
    at i (https://localhost:44344/jspm_packages/system.js:5:9594)
    at j (https://localhost:44344/jspm_packages/system.js:4:7455)
    at S (https://localhost:44344/jspm_packages/system.js:4:6914)
    at x (https://localhost:44344/jspm_packages/system.js:4:5952)
    at https://localhost:44344/jspm_packages/system.js:5:6510`

It is caused by this piece of code https://github.com/aurelia/framework/blob/master/dist/amd/aurelia-framework.js#L17 which used to work fine for SystemJs 0.19.

I've found this commit https://github.com/ModuleLoader/es-module-loader/commit/f2bb1395231e017594dd2e2ff94af5086a92c854 which seems to have caused my issue.

It might be that I am missing some vital configuration. Any advice would be appreciated.

**Comment by guybedford** [comment]
Ok I've added a possible fix for this in https://github.com/ModuleLoader/es-module-loader/commit/e081e5b1521a90c7590875161641b1a8f5585204 pending release.

**Comment by MaximBalaganskiy** [comment]
👍  Thanks, I'll test this patch tomorrow - 11pm here :)

**Comment by guybedford** [comment]
Released in 2.1.1 and SystemJS 0.20.8. Just let me know if you're still noticing this.

**Comment by MaximBalaganskiy** [comment]
The fix worked, thanks. Is it possible to tell jspm to use the latest SystemJS release?

**Comment by guybedford** [comment]
Thanks for the update here, I'll post the SystemJS release out in jspm shortly.

**Comment by MaximBalaganskiy** [comment]
You might want to have a look at another issue first https://github.com/systemjs/systemjs/issues/1588
