### ISSUE TITLE
warning es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.

### ISSUE THREAD

**Issue by lucas-viewup** [ModuleLoader/es-module-loader#535]
Hi there! I was using es6-module-loader when I notice this message in npm installation:

```
warning es6-module-loader@0.17.11: This project has been deprecated for "npm install es-module-loader" based on the newer loader spec.
```

Can you recommend another way to load modules? I tried with 'es-module-loader' but I don't know which script I should include in script tag in HTML. Thanks!

**Comment by guybedford** [comment]
SystemJS is the most popular loader to use based on this project (http://github.com/systemjs/systemjs).
