### ISSUE TITLE
Problem resolving relative URL like '../..'

### ISSUE THREAD

**Issue by roman-petrov** [ModuleLoader/es-module-loader#536]
When upgrading SystemJS dependency I encountered a problem related to es-module-loader related to commit 
https://github.com/ModuleLoader/es-module-loader/commit/5c23a11b412d66dd3861f0a42c387e44a5eab100#diff-99b2b3749b74bdf15be5f4ded2c4324a.

In version below 2.2.4:

`resolveIfNotPlain('../..', 'path/to/test/module.js')` returns a string `"path/"`

After 2.2.4 due to changes in commit above:

`resolveIfNotPlain('../..', 'path/to/test/module.js')` returns a string `"path/to/.."`

Can you please clarify, is this a bug or planned breaking change in 2.2.4 ?...

Many thanks!

**Comment by guybedford** [comment]
Thanks, I've added this back in https://github.com/ModuleLoader/es-module-loader/commit/4c9a9ff0d20ed5827f950b7422194e3080998fab.

**Comment by guybedford** [comment]
Released in 2.2.8.

**Comment by roman-petrov** [comment]
Thank you very much for the update!
